# pid参数
imu_roll_p: 2.3  # 2
imu_roll_i: 0.3  # 0.1
imu_roll_d: 0.22   # 0.1
imu_pitch_p: 1  # 1
imu_pitch_i: 0.4 # 0.1
imu_pitch_d: 0.25  # 0.1
imu_yaw_p: 1 # 未使用
imu_yaw_i: 0 # 未使用
imu_yaw_d: 5 # 未使用