# pid参数
imu_roll_p: 0.05  # 2
imu_roll_i: 0  # 0.1
imu_roll_d: 0.01   # 0.1
imu_pitch_p: 0.1  # 1
imu_pitch_i: 0 # 0.1
imu_pitch_d: 0.02  # 0.1
imu_yaw_p: 1 # 未使用
imu_yaw_i: 0 # 未使用
imu_yaw_d: 5 # 未使用

# 步长 步宽 m 步宽0.7*2
walk_length: 0.05
walk_width: 0.12

# 脚步抬高 m
foot_hight: 0.05

# 向驱动版发送帧的间隔时间 s
walk_frame_T: 0.02

# pre-load centroid hight m
c_h_para: 0.35

# local ip address
local_ip_addr: "192.168.186.132"